#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE DATABASE users_db;
    CREATE DATABASE products_db;
    CREATE DATABASE orders_db;
    GRANT ALL PRIVILEGES ON DATABASE users_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE products_db TO $POSTGRES_USER;
    GRANT ALL PRIVILEGES ON DATABASE orders_db TO $POSTGRES_USER;
EOSQL
